spring:
  application:
    name: microservicio-zuul
server:
  port: 7000
zuul:
  routes:
      serv-usuarios: # Service to create as sample
        path: /api/alumnos/** #path that will be intercepted
        serviceId: microservicio-usuarios
        #url: http://localhost:9000
      serv-cursos: # Service to create as sample
        path: /api/cursos/** #path that will be intercepted
        serviceId: microservicio-cursos
        #url: http://localhost:9000
      serv-examenes: # Service to create as sample
        path: /api/examenes/** #path that will be intercepted
        serviceId: microservicio-examenes
        #url: http://localhost:9000
      serv-respuestas: # Service to create as sample
        path: /api/respuestas/** #path that will be intercepted
        serviceId: microservicio-respuestas
        #url: http://localhost:9000
      
eureka:                  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka